kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-app-deployment
  namespace: {{ .Values.namespace_name }}
  labels:
      app: {{ .Values.labels }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.selector }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels }}
        version: v1
    spec:
      containers:
      - name: {{ .Values.container }}
        image: {{ .Values.registry_name }}/{{ .Values.image_name }}:{{ .Values.image_tag }}
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 5000
            protocol: TCP
      restartPolicy: Always