kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-app-deployment
  namespace: {{ .Values.namespace_name }}
  labels:
      app: hello-app
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-app
        version: v1
    spec:
      containers:
      - name: hello-app
        image: {{ .Values.registry_name }}/{{ .Values.image_name }}:{{ .Values.image_tag }}
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 5000
            protocol: TCP
      restartPolicy: Always