kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service_name }}
  namespace: {{ .Values.namespace_name }}
  labels:
    app: {{ .Values.labels }}
spec:
  selector:
    app: {{ .Values.selector }}
  ports:
    - port: 5000
      name: http
  type: {{ .Values.service_type }}