apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo/helm-hello-app
    repoURL: https://github.com/PovilasGT/inkodus-home-test
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true