registry_name: "078745329950.dkr.ecr.us-east-1.amazonaws.com"
image_tag: "55cc490659ee515cd9ca70d444787e3ab07556be"
image_name: "hello-app"
container: "hello-app"

labels: "hello-app"
selector: "hello-app"

namespace_name: "dev"

# service
service_name: "hello-app-svc"
service_type: "NodePort"
