registry_name: "078745329950.dkr.ecr.us-east-1.amazonaws.com"
image_tag: "e195eef8f5e5ff198143ae56cb5df6ae9ccaa866"
image_name: "hello-app"

# all
namespace_name: "dev"

# service and route
service_name: "hello-app-svc"

service:
  type: ClusterIP
  port: 5000
